import React, { useEffect, useState } from 'react';
import { FileText, Download, Calendar, Clock, X, Check } from 'lucide-react';
import { format } from 'date-fns';

type Report = { id: string; title: string; date: string; size: string; type: string };

const makeReports = (): Report[] => Array.from({ length: 6 }).map((_, i) => ({
  id: `REP-2024-${10 - i}`,
  title: `Weekly Threat Summary - Week ${10 - i}`,
  date: format(new Date(Date.now() - i * 7 * 24 * 3600000), 'MMM dd, yyyy HH:mm:ss'),
  size: `${(Math.random() * 2 + 1).toFixed(1)} MB`,
  type: 'PDF'
}));

const downloadReport = (report: Report) => {
  const content = [
    'SENTRY-AI SECURITY REPORT',
    '==========================',
    `Report: ${report.title}`,
    `Report ID: ${report.id}`,
    `Generated: ${report.date}`,
    `Format: ${report.type}`,
    `Estimated Size: ${report.size}`,
    '',
    'Summary',
    'This report was generated by SENTRY-AI and contains the current threat-monitoring summary.',
    'Use the Dashboard and Alert Log for live anomaly details.'
  ].join('\n');
  const blob = new Blob([content], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${report.id}-security-report.pdf`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
};

export default function Reports() {
  const [reports, setReports] = useState<Report[]>(makeReports());
  const [showSchedule, setShowSchedule] = useState(false);
  const [schedule, setSchedule] = useState('weekly');
  const [scheduleTime, setScheduleTime] = useState('09:00');
  const [scheduleSaved, setScheduleSaved] = useState(false);

  useEffect(() => {
    const interval = setInterval(() => {
      setReports(current => [{
        id: `REP-LIVE-${Date.now()}`,
        title: `Live Threat Summary - Event ${current.length + 1}`,
        date: format(new Date(), 'MMM dd, yyyy HH:mm:ss'),
        size: `${(Math.random() * 2 + 1).toFixed(1)} MB`, type: 'PDF'
      }, ...current].slice(0, 12));
    }, 10000);
    return () => clearInterval(interval);
  }, []);

  const saveSchedule = (e: React.FormEvent) => {
    e.preventDefault();
    localStorage.setItem('sentry-report-schedule', JSON.stringify({ schedule, scheduleTime }));
    setScheduleSaved(true);
    setTimeout(() => { setScheduleSaved(false); setShowSchedule(false); }, 1200);
  };

  useEffect(() => {
    try {
      const saved = JSON.parse(localStorage.getItem('sentry-report-schedule') || 'null');
      if (saved) { setSchedule(saved.schedule || 'weekly'); setScheduleTime(saved.scheduleTime || '09:00'); }
    } catch { /* ignore malformed local data */ }
  }, []);

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div><h1 className="text-2xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">Automated Reports</h1><p className="text-slate-400 text-sm">Scheduled analytics and compliance reports.</p></div>
        <button onClick={() => setShowSchedule(true)} className="flex items-center gap-2 bg-blue-600/20 border border-blue-500/50 text-blue-400 hover:bg-blue-600 hover:text-white px-4 py-2 rounded-lg text-xs font-mono uppercase tracking-widest transition-colors"><Calendar className="w-4 h-4" /> Schedule New</button>
      </div>

      {showSchedule && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={e => { if (e.target === e.currentTarget) setShowSchedule(false); }}>
        <form onSubmit={saveSchedule} className="w-full max-w-md bg-[#0f111a] border border-white/10 rounded-2xl p-6 shadow-2xl">
          <div className="flex justify-between items-center mb-6"><h2 className="text-lg font-semibold text-slate-200">Schedule Report</h2><button type="button" onClick={() => setShowSchedule(false)} className="p-2 text-slate-500 hover:text-white"><X className="w-5 h-5" /></button></div>
          <label className="block text-[10px] uppercase tracking-widest text-slate-500 mb-2">Frequency<select value={schedule} onChange={e => setSchedule(e.target.value)} className="mt-2 w-full bg-[#0a0c14] border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>
          <label className="block text-[10px] uppercase tracking-widest text-slate-500 mb-6">Time<input type="time" value={scheduleTime} onChange={e => setScheduleTime(e.target.value)} className="mt-2 w-full bg-[#0a0c14] border border-white/10 rounded-lg px-3 py-2 text-sm text-slate-200" /></label>
          <button type="submit" className="w-full flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-500 text-white py-2 rounded-lg text-sm">{scheduleSaved ? <><Check className="w-4 h-4" /> Saved</> : 'Save Schedule'}</button>
        </form>
      </div>}

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reports.map(report => <div key={report.id} className="bg-[#0f111a] rounded-xl p-6 border border-white/5 shadow-lg group hover:border-white/10 transition-colors">
          <div className="flex items-start justify-between mb-4"><div className="p-3 bg-blue-600/10 rounded-lg text-blue-500 border border-blue-500/20"><FileText className="w-5 h-5" /></div><span className="px-2 py-1 bg-white/5 border border-white/10 text-slate-400 text-[10px] font-mono uppercase tracking-widest rounded">{report.type}</span></div>
          <h3 className="font-semibold text-slate-200 mb-2">{report.title}</h3>
          <div className="space-y-2 mb-6"><div className="flex items-center gap-2 text-xs font-mono text-slate-500"><Clock className="w-4 h-4 text-slate-600" /><span>{report.date}</span></div><div className="flex items-center gap-2 text-xs font-mono text-slate-500"><FileText className="w-4 h-4 text-slate-600" /><span>{report.size}</span></div></div>
          <button onClick={() => downloadReport(report)} className="w-full flex items-center justify-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/5 hover:border-white/10 text-slate-300 rounded-lg text-[11px] font-mono uppercase tracking-widest transition-colors"><Download className="w-4 h-4" /> Download</button>
        </div>)}
      </div>
    </div>
  );
}
